addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python

python:
  - '2.7'

virtualenv:
  system_site_packages: true

env:
  matrix:
  - VERSION="8.0" LINT_CHECK="1"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
  - VERSION="8.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"
  - VERSION="8.0" DOCS="1" LINT_CHECK="0"
  global:
    secure: "lazdZGpkqFTQiu44grYAqKcaGh0cVTBlrHcBxxs43K/OH4Uc2AjMBty83zKc0ZgzizrNOsfK3Z3UHLmTNI92Vi3PtgGzA9dUmiReGO6QcE9P31Geg4pN/1Fwosv6aSpG3hejJJ8ZYpMbEPJkZyjTVpdM2r1VEcqEvFQ2xR5bEUg="
    secure: "LOTy5vySx9VQyCq1Fs/sqSy6xNzNk0vN5YoFIA1dkoX44ME11kWCcirjPk2+eMwNNHSwScImZU88ozdjOaQCkHqSTmhr932VQl7DJNhYanGX7KCngwJ/mAgpfYZzhmxFjLjV7c8YfURQWKvKcln7Oee03+Xqe2SgC/1vxRkBMdQ="

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install sphinx sphinx_bootstrap_theme sphinx-intl odoo-sphinx-autodoc

services:
  - postgresql

script:
  - if [ -z "$DOCS" ] ; then travis_run_tests; fi
  - if [ -n "$DOCS" ] ; then ./.travis_build_doc; fi

after_success:
  - if [ -z "$DOCS" ] ; then coveralls; fi
  - if [ -n "$DOCS" ] ; then ./.travis_push_doc; fi
